AspNetCshart/ListadoDatosSimulado/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ListadoDatosSimulado.Models
{
    public class Persona
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string aPaterno { get; set; }    
        public string aMaterno { get; set; }
    }
}

AspNetCshart/ListadoDatosSimulado/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ListadoDatosSimulado.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AspNetCshart/ListadoDatosSimulado/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ListadoDatosSimulado.Models;

namespace ListadoDatosSimulado.Controllers
{
    public class PersonaController : Controller
    {
        Random ran = new Random();

        List<Persona> lista = new List<Persona>();
        // GET: Persona
        public ActionResult Index()
        {
            for(int x=0; x<10; x++)
            {
                ListadoPersonas();
            }

            return View(lista);
        }

        public void ListadoPersonas()
        {
            Persona per = new Persona();
            string[] nombres = new string[] { "Vicente", "Ignacio", "Dante", "Arial", "Sonia", "Yesmenia" };
            string[] aMater = new string[] { "Garate", "Piñeda", "Rifo", "Vergara", "Parez", "Gonzalez" };
            string[] aPater = new string[] { "Garate", "Piñeda", "Rifo", "Vergara", "Perez", "Gonzalez" };

            per.codigo = ran.Next(1, 20);
            per.nombre = nombres[ran.Next(0, nombres.Length)];
            per.aMaterno = aMater[ran.Next(0, aMater.Length)];
            per.aPaterno = aPater[ran.Next(0, aPater.Length)];

            lista.Add(per);

        }
    }
}

AspNetCshart/ListadoDatosSimulado/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AspNetCshart/ListadoDatosSimulado/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AspNetCshart/ListadoDatosSimulado/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AspNetCshart/ListadoDatosSimulado/Views/Persona/Index.cshtml
@model IEnumerable<ListadoDatosSimulado.Models.Persona>

@{
    ViewBag.Title = "Index";
}

<h2>Listado de PERSONAS</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.codigo)*@
            Código
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.nombre)*@
            Nombre
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.aPaterno)*@
            Apellido Paterno
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.aMaterno)*@
            Apellido Materno
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aPaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aMaterno)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

AspNetCshart/ListadoDatosSimulado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Lista de personas","Index","Persona")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>